# Generated by Django 4.1 on 2022-09-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('address', models.TextField(max_length=150)),
                ('state', models.CharField(max_length=15)),
                ('zip', models.IntegerField()),
                ('mark', models.BooleanField(default=False)),
            ],
        ),
    ]
